version: 0.2

phases:
  install:
    commands:
      - yum install -y maven
  build:
    commands:
      - mvn clean package -DskipTests

artifacts:
  files:
    - target/upload-app.jar
    - appspec.yml
    - scripts/**/*
